### ISSUE TITLE
Can't access my subdomaine

### ISSUE THREAD

**Issue by mourad1974** [susanBuck/dwa15-spring2018#11]
Hi everyone,
I followed all the steps as described, pinged my subdomain and it returned the right Ip address .

I can access my app www.mydwa15.me/P1 but not www.p1.mydwa15.me
tried megaproxy- cleared cache in browser and Mac...

the Vhost that I added 

<VirtualHost *:80>
  ServerName p1.mydwa15.me
  DocumentRoot "/var/www/html/P1”
  <Directory "/var/www/html/P1”>
    AllowOverride All
  </Directory>
</VirtualHost>

**Comment by reelmatt** [comment]
The problem seems to be with capitalization and "P1" vs. "p1". For example, going to <http://www.mydwa15.me/P1> **works**, but <http://www.mydwa15.me/p1> (lowercase) does **not** work.

Trying the same for the subdomain doesn't appear to be working (my browser auto-changes P1 to p1). My suggestion would be to try changing everything to lowercase, see if that works?

**Comment by mourad1974** [comment]
Thank you for your prompt reply, which I appreciate, I already tried lowercase with hello-world.mydwa15.me and I have the same issue too.


Thank you,

Mourad Saleh

________________________________

**Comment by susanBuck** [comment]
Can you share a screenshot of your DNS settings?

**Comment by mourad1974** [comment]
![screen shot 2018-02-08 at 1 13 23 pm](https://user-images.githubusercontent.com/35425870/35990405-e8ce62aa-0cd1-11e8-898a-04a1767693d2.png)

**Comment by susanBuck** [comment]
Thanks - everything looks good there.

Note that when attempting to access your subdomain, you should omit the `www`.

So this: <http://p1.mydwa15.me>
Instead of this: <http://www.p1.mydwa15.me>

`www` is itself a subdomain, so it would need to be configured to work.

When I visit <http://p1.mydwa15.me> I'm getting a 404 Not Found:
<img width="591" alt="image" src="https://user-images.githubusercontent.com/237711/35991264-a6d43ebc-0cd4-11e8-9095-153f582707ad.png">

Can you do the following:
1. Share the entire contents of your `/etc/apache2/sites-enabled/000-default.conf` file from DigitalOcean - you can share it via [Gist](https://gist.github.com).
2. Confirm that you have restarted apache after saving changes to 000-default.conf (via `service apache2 restart`)
3. Navigate into your `/var/www/p1` directory and run the `ll` command to print the contents of this directory. Share the output of this command with us.

**Comment by tflinthbs** [comment]
Hi @mourad1974, not sure if this got resolved, I had similar issue, replacing the quotation marks right after `DocumentRoot "/var/www/html/P1` and `<Directory "/var/www/html/P1` worked for me. Seems like they did not paste correctly when copied from the notes. Or you can copy below:



```
<VirtualHost *:80>
ServerName p1.mydwa15.me
DocumentRoot "/var/www/html/P1"
<Directory "/var/www/html/P1">
AllowOverride All
```

**Comment by mourad1974** [comment]
Thank you for replying, I still didn't resolve the issue.
I don't understand what do you mean by replacing the quotation marks because the code you wrote here is the same I have.

**Comment by susanBuck** [comment]
@mourad1974 Sometimes when you copy code samples from a website, it comes with or is translated to "curly quotes" instead of "straight quotes"

To learn about the difference between the two, read this: <http://smartquotesforsmartpeople.com>

For code/config file purposes, we want **straight quotes**. 

To ensure you have straight quotes, simply delete any quotes in your VirtualHost block and type them again in your code editor.

**Comment by susanBuck** [comment]
Follow-up - here's a screenshot highlighting the point @tflinthbs is making about your config:
<img width="375" alt="image" src="https://user-images.githubusercontent.com/237711/36076260-c67d7fb2-0f27-11e8-9a52-cb7333cd2e53.png">

**Comment by mourad1974** [comment]
Solved :)
Thank you so much for the help.
