### ISSUE TITLE
"Can't start Git" error in PhpStorm

### ISSUE THREAD

**Issue by gaderrick** [susanBuck/dwa15-spring2018#16]
Anyone using MS Windows and getting the following "pop up" error windows?

> Can't start Git: git.exe
> The path to Git executable is probably not valid.

I don't have git installed on the local OS (except for inside the cmder instance provided to the class). I also can't figure out how to disable/make the error go away in PhpStorm. I'm wondering if it is possible to use the git instance inside cmder, but I'm not sure how the environment for it will translate outside of the cmder shell.

Thoughts/solutions :)?

**Comment by aleksaleksiev** [comment]
As @johnpura says, PHPStorm needs to be pointed to your local Git installation to enable its Git integration. Although this integration isn't strictly necessary (you can still use Git via the command line), it does give you nice features such as highlighting files that have changed since the last commit in PHPStorm (which means you don't have to change windows and type `git status` or `git diff` just to check what changes you've made). 

The setting you'll want to change is in `File -> Settings -> Version Control -> Git -> Path To Git Executable`. You'll want to point it to `wherever_you_installed_cmder\vendor\git-for-windows\bin\git.exe`.

**Comment by ElijahMR** [comment]
I had Git previously installed via Github's application instead and on Windows at least the location of Git will be `C:\Users\<user>\AppData\Local\GitHub\PortableGit_<guid>\cmd\git.exe`

**Comment by oarangel** [comment]
I am using a MAC and had similar error messages following a **phpstorm** update, tried several things including changing the path settings mentioned above. Nothing worked.
I updated the git package and the problem went away. 
I read other users reinstalled **phpstorm** and the issue was resolved.

**Comment by susanBuck** [comment]
Closing this post due to inactivity, but feel free to continue the discussion or post a new thread if any problems are still pending.
