### ISSUE TITLE
Which type of Browser to Use 

### ISSUE THREAD

**Issue by mfaldas** [susanBuck/dwa15-spring2018#22]
Are there any pros and cons to using certain browsers when testing out our programs?  When following the lecture video last week, I inserted the Javascript into my Safari Browser and no alert came up.  But I see that in the lecture video that Mozilla was used and the alert came up.  Any suggestions on the best Browser to test locally?

**Comment by amushal** [comment]
I imagine the alert should have happened regardless of browser, unless you sanitized the input.  It is a personal preference really, I am used to Chrome and like the client side scripting/debugging interface.

**Comment by susanBuck** [comment]
It's possible Safari was adding its own level of XSS protection which prevented the alert from showing. I've noticed Chrome doing this as well. As we saw in lecture, this is not the case in Firefox (Mozilla).

Even though some browsers will prevent against XSS, it doesn't mean our applications shouldn't - because we never know what browser our visitors will use.

**As for which browser to use when testing -**
You can develop using whatever browser you prefer. As @amushal noted, that comes down to personal preference.

However, once you're done developing, it's common practice to test your site across multiple browsers to ensure it's operating as expected on multiple platforms.

For small, low traffic sites with low-frills CSS/JS, this can be as simple as manually running some tests in a variety of browsers. 

For large, high demand sites that are very rich in CSS and JS, you can set up entire testing infrastructures using things like https://crossbrowsertesting.com.

For the purposes of this course - it wouldn't hurt to double check your work in at least one other browser before submitting, especially if your layout is on the more complex side.

**Comment by archerdave** [comment]
I can verify that Chrome does some XSS checking by default, and that turning it off is a royal PITA.  If you want to test whether a XSS vulnerability *works against* your site, Chrome is not the browser for that test as it will stop the vulnerability for you, if it detects it.
