### ISSUE TITLE
adding a floatNumeric validator check to Form.php

### ISSUE THREAD

**Issue by hsayres** [susanBuck/dwa15-spring2018#26]
Hi all,

I want to extend Form.php to include a validation for user-inputed floats (i.e. 12.43). To that end, I made the following adjustments to *Form.php*

```php
    private function getErrorMessage($rule, $parameter = null)
    {
        $language = [
            'alphaNumeric' => ' can only contain letters or numbers.',
            'alpha' => ' can only contain letters.',
            'numeric' => ' can only contain numbers.',
            'floatNumeric' => ' can only contain float numbers.',
            'required' => ' can not be blank.',
            'email' => ' is not a valid email address.',
            'min' => ' has to be greater than ' . $parameter . '.',
            'max' => ' has to be less than ' . $parameter . '.',
        ];
        # If a message for the rule was found, use that, otherwise default to " has an error"
        $message = isset($language[$rule]) ? $language[$rule] : ' has an error.';

        return $message;
    }
```

and
```php
    protected function floatNumeric($value)
    {
        return is_float(str_replace(' ', '', $value));
    }
```

My validation code in logic.php looks like this:
```php
if ($form->isSubmitted()) {
    $errors = $form->validate(
        [
            'tabTotal' => 'required|floatNumeric',
            'splitNum' => 'required|numeric',
            'serviceLevel' => 'required',
        ]
    );
... #some more code
};
```

however, a user-inputed float is triggering the error _"can only contain float numbers"_, rather than passing the validation. 
(1) can anyone spot what I'm doing wrong so that a user-inputed float passes the _"floatNumeric"_ validation check and
(2) am I allowed to take the liberty to add additional validation checks directly to Form.php or should I create my own file for this?

**Comment by susanBuck** [comment]
@hsayres I tested your code and found the same unexpected behavior. Did a few tests and it appears that when you use `str_replace` it's converting your float number to a string.

Demo:
```php
$value = 1.5;

echo gettype($value); # Double (float)

echo gettype(str_replace(' ', '', $value)); # Now it's a String
```

There are a few solutions to address this under the *User Contributed Notes* section of the [is_float](http://php.net/manual/en/function.is-float.php) docs, for example:

> 
> If you want to test whether a string is containing a float, rather than if a variable is a float, you can use this simple little function:
> 
> function isfloat($f) return ($f == (string)(float)$f);

Using that, I came up with this variation of your code:

```php
<?php

function floatNumeric($value)
{
    return str_replace(' ', '', $value) == (string)(float)$value;
}

# Tests:
echo floatNumeric('1.5') ? 'yes' : 'no'; # Expected: yes
echo floatNumeric(1) ? 'yes' : 'no';     # Expected: yes
echo floatNumeric('1.5') ? 'yes' : 'no'; # Expected: yes
echo floatNumeric('abc') ? 'yes' : 'no'; # Expected: no
```

### Regarding editing Form.php
When utilizing outside code, it's generally best to avoid changing that code directly. If the developer of the outside code releases updates, it makes it difficult to update your version because you then have changes in it.

In this case, a better solution would be to create your own class that extends Form.php. This was a topic listed under "Extras" so I didn't cover it explicitly in lecture, but you can read more about it here: [Extending Form.php](https://github.com/susanBuck/dwa15-spring2018/blob/master/php/form.php-extending.md).

**Comment by hsayres** [comment]
Thanks so much!
