### ISSUE TITLE
Permission denied (publickey).

### ISSUE THREAD

**Issue by mamdooh26** [susanBuck/dwa15-spring2018#28]
I've formatted my computer and create a new pair of public and private key. The access to github worked properly but when I tried to access digital ocean I got permission denied. Does any one have a solution for this.

**Comment by archerdave** [comment]
Can you show us the commands that you are typing in and the output you get?

**Comment by susanBuck** [comment]
👍s @archerdave's request for commands and output. This kind of context never hurts for troubleshooting, no matter now insignificant or irrelevant it may seem.

That being said, I think I know what's going on here....

Before we created any Droplets on DigitalOcean, we stored a public SSH key in our DigitalOcean settings. Once we did this, we were able to indicate that our new Droplet should be set up with this key. (You can see that in the second to last step on [this image](https://camo.githubusercontent.com/e09f279f64d25a879d6dac3e9f0ee8d5eda93b38/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6d616b696e672d7468652d696e7465726e65742f76632d6469676974616c2d6f6365616e2d6e65772d64726f706c65744032782e706e67) from the notes.)

When you reformatted your computer, you lost the private key that goes with the public key stored on your DigitalOcean Droplet.

Because of this, you need to update your DigitalOcean server with your new public key.

I have instructions on how to do this because it's a multi-step process and typically happens to a small handful of students a semester - [here are the notes on how to fix this.](https://github.com/susanBuck/dwa15-spring2018/blob/master/servers-and-git/permission-denied-public-key.md)

**Comment by mamdooh26** [comment]
@susanBuck  thank you for help. It fixes the issue.
