### ISSUE TITLE
Following a second class implementation, I am unable to display the results

### ISSUE THREAD

**Issue by oarangel** [susanBuck/dwa15-spring2018#30]
i combined my own class BillSplit and Form.php. Now I am not to display the result. Code is not passing  data to the index.php file for display. **Recoverable fatal error: Object of class BillSplit\CalcSplit could not be converted to string in /Applications/MAMP/htdocs/P2/index.php on line 61**  
Github repository link is: [https://github.com/oarangel/P2](url)
I can display the **`billSplit`** variable at the Class and Logic files but I cannot pass the variable to the index file.

**Comment by mcm223** [comment]
I believe the issue is that you are using two variables, both named ```$billSplit```. In logic.php you are instantiating a new object of the CalcSplit class in one variable, and within CalcSplit you are declaring another variable called ```$billSplit``` that stores the results of that calculation. 

In **index.php** you are attempting to echo ```$billSplit``` on line 61, but it's referring to your object of the class instead of the variable with the results. That is why your error says the object cannot be converted to a string. I'd recommend changing your public variable name inside CalcSplit to avoid the naming conflict and see if that fixes the issue.

**Comment by susanBuck** [comment]
Closing this post due to inactivity, but feel free to continue the discussion or post a new thread if any problems are still pending.
