### ISSUE TITLE
Composer warning on Digital Ocean

### ISSUE THREAD

**Issue by gaderrick** [susanBuck/dwa15-spring2018#35]
Hi- 
Working through the notes/assignment this week I got the following "warning" on composer:
```
Do not run Composer as root/super user! See https://getcomposer.org/root for details
```
The commands run fine (although the webiste's guidance is ominous), but just wondering what the correct user to run this as (and what permissions this user needs) is. The user wwwdata (from digital ocean) can't be sudo'd to so thats out. Suggestions?

VR,
Jerry

**Comment by hsappa** [comment]
For what it's worth, I noticed that that particular message was also present in the videos.  I noticed it because I didn't see ti when I was using composer on DO and that caused me concern.

**Comment by susanBuck** [comment]
It's expected to see that message when running `composer install` on production, because we have been logging in as the `root` user. 

In a real-world application when working with important and/or sensitive data, it's suggested that you log in using an alternative user, and disable root access. The how/why of this is covered in these extra notes: [Increasing server security](https://github.com/susanBuck/dwa15-spring2018/blob/master/servers-and-git/increasing-server-security.md). If you use a not-root user, you should not see that ominous message.

Note, though, that if you create an alternative user right now, you'd have to alter the ownership of your existing directories, as they're owned by root (since root created them). [Here's a direct link to the section of the above mentioned note set that covers this.](https://github.com/susanBuck/dwa15-spring2018/blob/master/servers-and-git/increasing-server-security.md#change-ownership-of-varwwwhtml)

You should not see the message when working with composer locally, *unless* you are prefixing your commands with `sudo`.
