### ISSUE TITLE
Issues after updating php to 7.2.2

### ISSUE THREAD

**Issue by jaechong** [susanBuck/dwa15-spring2018#38]
Hi, I have two Issues after deploying foobooks in DO and upgrading php on MAMP.

## Issue 1:
After updating php on the server, or after following the instructions to deploy foobooks on DO, my project 1 and project 2 in DO are broken.  

After installation, I see these issues:

+ `http://my ip addr/info.php` - I get the content of info.php instead of the actual output of information
+ `http://my ip addr/foobooks/` - I also get the content index.php
+ `http://foobooks.jaechong.me` - I get the initial DO screen with a shark
+ `http://p1.jaechong.me` - random quote is not working
+ `http://p2.jaechong.me` - I get garbage characters and calculation for bill splitter does not work.
On local, p1 and p2 works fine after php 7.2.1 upgrade for MAMP. although I also experience issue 2 below for upgrading php on MAMP.

## Issue 2:
When I upgraded MAMP, I had to change the port to 8888 in order for it to work.  
It works if I do `http://localhost:8888/p1` however `localhost:8888/p1.loc` gives the following error:

> Not Found The requested URL /p1.loc was not found on this server.

When I update `httpd-vhost.conf` file to change all `*:80` to `*:8888`, even `http://loalhost:8888/p1` does not work.

Just curious, I think 7.1.12 is a later version than 7.1.3, it is not mandatory to update to php 7.2.1.  In any case, updating is important and doing this exercise while in the course is a good thing. (Though I hope we didn't have to do it at this time when I don't have much time to investigate)

Since this is an environment issue, I don't think it helps to provide my git repository

Any help would be greatly appreciated.

Thank you.

**Comment by bwilks26** [comment]
Hi @jaechong , I had a smilar problem when I upgraded my entire MAMP application, and not just after updating to PHP 7.2. I had to completely uninstall MAMP as there was some conflicts with the previous install, and it worked fine after a fresh copy was installed and the directions from week 2 were followed. Make sure to COPY your htdocs folder and your httpd-vhosts.conf file (from /MAMP/conf/apache/extra/httpd-vhosts.conf) and replace them into the fresh version of MAMP. Hope this helps!

**Comment by jaechong** [comment]
Thanks for the reply.  I guess you mean you had a similar issue as my issue2.  I guess I will have to do what you suggested soon or later but I have a very limited amount of time due to a personal situation so that I was trying to avoid that and redo everything later on when I have more time.  Thanks a lot for your suggestion.

**Comment by reelmatt** [comment]
As @bwilks26 mentioned, the MAMP upgrade will overwrite your vhosts file so make sure to copy that (or if you already upgraded, just follow [steps 1 and 2 here](https://github.com/susanBuck/dwa15-spring2018/blob/master/servers-and-git/local-domain.md#step-3-create-a-new-host). Your hosts file, [step 3](https://github.com/susanBuck/dwa15-spring2018/blob/master/servers-and-git/local-domain.md#step-3-create-a-new-host), shouldn't be changed, but you may want to take a look to make sure that's all still in order.

**Comment by jaechong** [comment]
Thank you Matthew.  I checked again and both httpd.conf and extra/httpd-vhosts.conf are updated as in the steps.  I found httpd.conf had the following additional lines not mentioned:

Listen 8888 
ServerName localhost:8888

Attached are files(changed to .txt to attach) that I changed to port 80.

[httpd.conf.txt](https://github.com/susanBuck/dwa15-spring2018/files/1763709/httpd.conf.txt)
[httpd-vhosts.conf.txt](https://github.com/susanBuck/dwa15-spring2018/files/1763711/httpd-vhosts.conf.txt)
[hosts.txt](https://github.com/susanBuck/dwa15-spring2018/files/1763749/hosts.txt)

PS, when I use markdown then Preview, I still see markdown characters instead of markdowns applied.  Is this normal?  I keep removing all markdowns after Preview since it still shows the markdown characters.

**Comment by susanBuck** [comment]
## Issue 1
1. Can you tell us what your DigitalOcean IP address is so we can test the URLs you've shared?
2. SSH into your DigitalOcean server and run `php --version` and report back to us what that outputs.

Based on everything you described, it looks like your server is no longer processing your PHP code. 
Report back on the above information and we will continue to troubleshoot this.

## Issue 2
I'm unsure why you're trying to use `http://localhost:8888/p1.loc` as an access point for your project. It's also no surprising that it does not work, because we've never seen instructions to get a URL like that to work.

We set up our local domains so we can use URL's like `http://p1.loc`, removing localhost from the picture. 

We can see this reflected in your hosts file:
```
127.0.0.1 p1.loc
```
So moving forward as we debug this, `http://p1.loc` (and likewise for p2) is the URL we want to focus on getting to work.

Let's also aim to get things working on port 80.
The `httpd.conf` you shared is set to listen on port 80. Leave that as is.
In the `httpd-vhosts.conf` you shared, your vhosts blocks are all set to port 80. Leave that as is.

**Here are two things I want you to do:**
1. In MAMP, go into your preferences and confirm Apache is set to port 80 and MySQL is set to port 3306.
<img width="536" alt="image" src="https://user-images.githubusercontent.com/237711/36743528-7f62a100-1bb8-11e8-944d-cffd3fd2f77e.png">

2. With those ports set, try to start your servers in MAMP. Let us know whether Apache starts or not. If Apache does not start, share the contents of `/Applications/MAMP/logs/apache_error.log` with us.

## Markdown issue
No, it is not normal to see the Markdown characters in Preview mode. I just edited your original post to add some Markdown syntax - I suggest clicking the Edit button to see the changes I made and see if it differs from the changes you were trying.

**Comment by susanBuck** [comment]
>> Just curious, I think 7.1.12 is a later version than 7.1.3, it is not mandatory to update to php 7.2.1. 

You're right. At first glance I read the version numbers as decimals where .30 > .12. : )

So if we go by Laravel requirements alone (7.1.3), a version upgrade is not essential. 

However, in a previous semester we had an issue where an older version of PHP was causing different versions of Laravel dependencies to be downloaded which caused discrepancies between our local and production servers. The upgrades we've made with MAMP and DO resolve these conflicts. 

Plus, as you noted, it's good practice. There are a lot of bug fixes that come with these version upgrades, so it's good to keep up to date when possible.

**Comment by jaechong** [comment]
Thank you for your reply.

# Issue1

1. My DO ip address is :` 159.65.34.169`
2. root@dwa-spring2018:~# `php --version
PHP 7.2.2-3+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Feb  6 2018 16:11:23) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.2-3+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies`
3. `php -r 'phpinfo();'`
The output is attached:
[phpinfo.txt](https://github.com/susanBuck/dwa15-spring2018/files/1765021/phpinfo.txt)

I will get back to work on this after 11 p.m. today.  I will go through step by step again.

# Issue2
**Issue 2 has been resolved.**  Thank you.  I don't know why I start using `http://localhost:8888/p1.doc`.  I think I tried `http://localhost/p1/` and when it did not work, I start changing the port and after using `http://localhost:8888/p1/` to work, I used `http://localhost:8888/p1.doc` thinking I need to specify the port separately.
Anyways, I cannot recall every steps but one dumb mistake I made for sure is when I added `virtualHost` section for `foobooks` in `httpd-vhosts.conf`, **I just cut and pasted the one from the instruction and missed the note and forgot to change for Mac**.  Most other instructions showed both windows and mac settings and I just blindly cut and pasted.  When it did not work, I started doing changes and cannot recall all the things but I think I also deleted one entry for 'localhost' when I deleted one for `foobooks` in `httpd-vhosts.conf`.
**After adding correct entries for both `localhost` and `foobooks` in `httpd-vhosts.conf`, it works fine now**.
Since the issue is fixed, I think it was a good exercise to update because I kind of blindly used MAMP and now I have a little more understanding with settings.

**Comment by jaechong** [comment]
# issue 1
**Resolved** 
I reinstalled php 7.2 again and everything is working now.  Both p1 and p2 project works fine too.
I am not sure what dumb mistake I may have made but it is all good now.
Thank you Susan and everyone for your help.
