### ISSUE TITLE
How to call an overridden function

### ISSUE THREAD

**Issue by archerdave** [susanBuck/dwa15-spring2018#39]
Given something like
```php
namespace Foo;
class Faz
{
    protected function jumble() //or should it be private?
    {
        return true;
    }
}
```
and
```php
namespace Bar;
class Baz extends Faz
{
    protected function jumble() // or should it be private?
    {
        return false;
    }
}
```
and
```php
$thingamajig = new $Baz()
$result = $thingamajig->jumble();
```
How do you specify which version of ```jumble()``` you want to use?

**Comment by susanBuck** [comment]
From the context of the object (outside) the class, there's no way to invoke the parent (Faz) jumble since it was overridden by the child (Baz) jumble.

However, it is possible invoke the parent classes method from within the child class like so:
```
namespace Bar;
class Baz extends Faz
{
    protected function jumble() 
    {
        parent::jumble();
        return false;
    }
}
```

This allows you to inherit all the functionality of the parent jumble, with the flexibility to add your own functionality on top of that.

**Comment by archerdave** [comment]
Well, I thought that's what I had set up, but I'm seeing the output of the method from the parent class, not the extended class.   Let me adjust (and clarify) the example a bit.

```php
namespace Foo;
public class Faz
{
    protected function jumble()
    {
        toss();
    }

    private function toss()
    {
        return false;
    }
}
```
```php
namespace Bar;
public class Baz extends Faz
{
    private function toss()
    {
        return true;
    }
}
```
```php
$thing = new Baz();
$result = $thing->jumble();
```

**Comment by susanBuck** [comment]
First, this code won't work as written because `jumble` is protected, meaning it can only be invoked from either Faz or Baz. Invoking it from outside the class, in the context of the object, will fail:
```php
$result = $thing->jumble(); # Can't do this b/c jumble is protected
```
To get around this, change `jumble` to be `public`.

That aside, I've worked up an example with some demos to show how a parent class can invoke a child class' method, which is what I think you're trying to do?

## Parent class Faz
```php
<?php
namespace Foo;
class Faz
{
    public function jumble()
    {
        # Whether this invokes Faz's toss or Baz's toss depends on
        # whether we're accessing this method via Faz or Baz, as shown in the 
        # examples below
        return $this->toss();
    }

    public function toss() {
        return 'Hi from Faz';
    }

}
```

## Child class Baz
```php
<?php
namespace Bar;

use Foo\Faz;

class Baz extends Faz
{
    public function toss()
    {
        return 'Hi from Baz';
    }
}
```

## Examples
```php
<?php
require 'Faz.php';
require 'Baz.php';

use Foo\Faz;
use Bar\Baz;

# New object of Baz, which is a child of Faz
$baz = new Baz();

# The following invokes `jumble` from parent Faz, because child Baz has no `jumble` method.
# Within jumble, $this->toss is invoked...
# child Baz *does* have a `toss` method which overrides
# parent Faz's `toss` method, and the results are we see "Hi from Baz"
echo $baz->jumble(); # "Hi from Baz"

# Now we create a new object from the parent Faz, so Baz is not
# factored into the picture at all
$faz = new Faz();

# Invokes Faz's `jumble`, which again invokes $this->toss
# but this time it's the `toss` method within Faz that is invoked,
# and the results are we see "Hi from Faz"
echo $faz->jumble();
```

**Comment by archerdave** [comment]
First, you are correct that ```jumble()``` is ```public```.  My mistake.  Second, your examples have all the demo functions being ```public```.  I'm not sure if I'm supposed to be editing that, as it's not my file.  I'm trying to extend Form.php.  I have successfully added an error checking method.  I'm also trying to overrride the ```getErrorMessage()``` method to provide meaningful feedback on the new check type.  The method's behavior, and a few ```echo``` statements tell me I'm not reaching the method in the child class.

**Comment by susanBuck** [comment]
>> the methods set as public, but I'm not sure if I'm supposed to be editing that part of the method in the parent class, as it's not my file. I'm trying to extend Form.php. 

Ah, I see. I was constructing my answers with the examples you provided (Faz/Baz) where, without further context, there was no way to determine what should be public/private/protected.

Moving on to the rest of your comment - 

You've hit a road-block with `Form.php` - It is extendable to allow new validation methods, but because the `getErrorMessage` is private, that portion of the class is not extendable.

When you hit a road-block with outside code like this you have some options:

If it's open source, submit an Issue or pull request to the original project, asking them to reconsider the design. They may agree and implement the change. They may disagree if there are underlying reasons for why they designed things the way they did.

In the context we're in, since I'm the "author" of Form.php, the equivalent is raising the issue to me, which you've effectively done here. :-) 

I'm on the fence as to whether `getErrorMessage` should be protected (and thus extendable). I purposefully left out the ability to specify custom error messages in Form.php with the intentions of keeping the class very basic for learning purposes. (I knew that later when we got to Laravel, a more real-world tool, we'd have the ability to do custom messages, so it didn't feel essential for P2.)

In short, Form.php was designed with this limitation in mind, for a very specific audience. If you get to the point where you want custom error messages, I don't think the answer is extending Form.php, but instead moving on to better tools for the job. 

So what do you do when you hit a road-block with outside code and the author does not want to change it? (Or maybe they're no longer maintaining the code and they don't respond to your request for the change?)

Your options then include seeking alternative tools, or forking the code and customizing it as you see fit. Of course this means you're loosing the opportunity to easily update the code should the author release updates, but these are all factors to consider when deciding what to do.

>> Is there a way I can approach this that will work, or should I just skip over this idea in this particular environment?

You're not missing anything - Form.php isn't designed to be extended like you're trying to extend it. 
If you're working on some other project right now where you need form validation with custom errors, I recommend making your own copy of Form.php and customizing it how you want. Or wait until we get to validation in Laravel. :-)

**Comment by archerdave** [comment]
Searching further, I found [this PHP documentation](http://php.net/manual/en/language.oop5.visibility.php) discussing visibility.  It seems that given the design of the class with the private method, I cannot override the private method in a child class.

**Comment by susanBuck** [comment]
@archerdave Good reference to round out this discussion!
