### ISSUE TITLE
Introduce yourself...

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/dwa15-spring2018#4]
Hi everyone - 

I thought I'd kick off a post where everyone can reply with an introduction to themselves so we can get to know each other. Tell us what brought you to this course and any other details you care to share.

A little bit about myself - this is my 10th semester teaching this course at the Extension School. In the past, I've taught at various other schools - Wellesley College, UPenn, UMiami. When working in industry I was the head developer for an online e-commerce store - [Photojojo](http://photojojo.com). Up until this past year, I was the co-president of an initiative called the Women's Coding Collective, which was aimed at getting more women and other under-represented minorities into programming. These days, I've been splitting my time between working on this course and building web services/tools for instructors.

All in all, I love creating things with code and teaching others how to do the same.

Looking forward to getting to know you all!

**Comment by tifilipdifisil** [comment]
Hi everyone my name is Philippe,
I'm originally from Haiti move here about 7 years ago. I've been in the IT field for over 10 years now. So it all started as a project I wanted to build a personal home server that I saw at a friend and taught it was cool. Ever since I got really curious on how a server work, how to manage it. I started with online documentation and asking questions to the back end web developers at work any time I wanted to do or fix something. I got more and more curious so here in my journey of hopefully becoming a back end developer myself. I have a good background in Java language still working on getting better. I’m married to a wonderful woman and from that came a wonderful girl. I bike, sail a lot and a little swimming typical habit of an island man. I’m and avid lover of scotch, beer and all type of cuisine. I love music and listen to all genre but my favorite are Kompa (Haitian music genre), Jazz, afro-Cuban jazz and House music. And I’m very excited about this class thank you already to Prof Buck and all the TA’s for the knowledge that I hope to extract from your brains. Not sure if I said the last line right but you get the idea.

**Comment by mourad1974** [comment]
Hi,
my name is Mourad, I am taking this course to toward a web technology certificate, in the country where I come from I worked as a Print graphic designer for more than 12 years, I am trying to adapt the market and have some web experience. I took the E12 and I need the E15 to combine them in order to take the E34, I love UX design, I'm excited taking to take the E15 :)

**Comment by voggi** [comment]
Hi there,

I'm Nicolas. Nice to meet you all.

I am from Germany, studied maths and have a background in the financial services industry. After uni, I started my career in the sales & trading and capital markets divisions of an American bank in London. Now I live back in Germany and work for an energy company managing their financial portfolios.

I picked up a few programming skills at uni and at work and I've always enjoyed coding. This is an attempt to approach things in a more structured and thorough way.

I am looking forward to it!

**Comment by brianyingling** [comment]
Hi everyone,

I'm Brian. Glad to meet you. 

I've been working in web development for about 4 years now, after making a pretty substantial career change and attending a bootcamp. There I learned Ruby on Rails but my day job consists of mostly dealing with Javascript. 

I'm taking this course because I'm interesting in learning PHP. I'm also interested in the master's program in software engineering and I thought this course would be a great fit in helping me get back into the academic world and to see if I wish to pursue the program.

Glad to be here!

**Comment by ElijahMR** [comment]
Hello everyone,

My name is Elijah and it is a pleasure to make your acquaintance.

I have dabbled in front end web design in the past few years but recently began exploring back end development in order to become a full stack web developer. I thought this course would be the perfect companion to my own research and so here I am.

I look forward to talking with all of you via this issues forum in the coming weeks.

**Comment by gaderrick** [comment]
Hello all- 

My name is Jerry, and I'm excited to be a part of this class and finally getting around to pursuing my graduate degree. 

A little about myself- I've worked in just about every computer related field during my 20+ year career but after my BS degree in computer science, most of my learning has been self taught because of a need to get something done. Currently, I'm the CTO of a small company that provides cybersecurity services to companies through the use of analytics and big data platforms.

I'm looking forward to working with you all to sharpen some old skills (the last time I programmed PHP was 10+ years ago), and to learn the "correct way" :) to program websites and web applications using new tools and methodologies.

**Comment by mfaldas** [comment]
Hi All,

My name is Marc-Eli Faldas.  Most people just call me Marc.

I earned my ALB in Computer Science at the Extension School back in 2016.  While at the Extension School, I joined a Harvard Innovation Lab startup called [Quantly](https://www.quantly.io) that specializes in Data Science. The group is involved with SpaceApps, a NASA incubator innovation program.  In addition to my Computer Science studies, I took courses that would fulfill the prerequisites for medical school.  Since graduation, I have been working at a private clinical research  company that specializes in Phase I-IV neurology, women's health and general medicine clinical trials.   In addition, I have been serving as a volunteer Director at a non-profit called [NANAY](nanay.com) that provides programs for Elders and Youth, Foreclosure Mitigation Services and Citizenship Workshops to the South Florida community.  I continue to work as a Junior Developer at Quantly.  We hosted two hackathons at Harvard, one in 2016 and another one in 2017.  You can check out the event website of the one we hosted in 2017 [here](https://www.quantlyhackathon2017.org).  We are currently planning the 2018 Hackathon.  These days, I use my free time to develop my skills as an Amateur Boxer.  Maybe I'll turn pro one day!

I was recently accepted into medical school and plan to attend in the Fall of 2018.  I am taking this class to refine my skills as a developer.  Feel free to reach out if you would like collaborate, have any tips or just want to chat about anything!  I wish you all the best of luck in this course.

**Comment by jspaul2003** [comment]
Hi Everybody,

My name Is Jean-Sebastien, but I go by JS.

I live in London and ny native language is French, but I also go by in English and Vietnamese. Struggling with the Chinese. I am a classics students, with a love for History,math and Latin. I however decided it was time to upgrade mys skillset and to start learning how to program, which turns out to be a lot of fun.I did a first class in CSCI -12, but I hope this class will enable me to develop my abilities further, particularly in PhP and Data access from a website. With time, I would like to move into Biology and Big Data. One step at a time...

Looking forward to learn with all of you.

JS

**Comment by balkasem** [comment]
Hi everyone,

My Name is Osama Balkasem, I go by Sam sometimes.

I moved to the US four years ago after living in Jordan, Saudi Arabia, and Turkey; currently, I work as a software developer for Pets Supplies Plus in the corporate office in Livonia Michigan. I have a goal of taking two fundamental classed that would qualify me to apply for the master program in the Extension school; as well as polishing my programming skills. I have a bachelor degree in Management Information System from Philadelphia University.

Happy to have my first course in the extension school, and happy learning for everyone.

Osama

**Comment by mildredfakoya** [comment]
Hi, Everyone. My name is Mildred Fakoya. I am a Nigerian, resident of Saint Vincent & the Grenadines. I am taking this course as one of the requirements that will qualify me to apply for a master in Software engineering. I have a degree in computer science plus some Microsoft certifications. I am currently a software developer for health information systems but I crave to learn more.

**Comment by amushal** [comment]
Hi there, my name is Ala Mushal and I live in beautiful San Diego.  Ever since I graduated in Computer Science back in 1995, I have extensively been working with passion in software development.  

I am currently the Director of Engineering in the health industry where we largely focus on remote patient monitoring, "Telehealth" technologies and management of Clinical Research trials.

I am eager to learn new cool technologies and will strive for continued excellence.  Looking forward to working with you all.

Best,
Ala

**Comment by hsappa** [comment]
Hi all,

I go by Paul.  I've been developing software and been involved in IT for over a decade now, but my original schooling was in Philosophy.  I can attest that an autodidact has alternately the best and the worst teacher so I'm hoping some formal training can fill in the gaps that I've never sought to explore.

I'm originally from Southern California (born in LA, went to school in San Diego and didn't want to leave) but have recently transplanted to Florida.  My wife's family all lives in Korea and so we travel back there as often as we can.  If anyone wants to practice grade school Korean, perhaps we can help each other out.

Good studies to all!
Paul

**Comment by smaaliki** [comment]
Hi Everyone,

This is **Samer Maaliki** checking in from (It's always sunny in) Dubai. I am currently a *Senior Consultant* at the *Executive Council of Dubai* and I work for a department that is responsible for improving customer services across all government entities.  Naturally, most services these days are provided online (websites and mobile apps), so a lot of my work involves dealing with the digital realm.  I am also in charge of developing an online and centralized service catalogue portal for all of the government agencies in Dubai among other things.

I have a BS from Boston University and a MS from University of Miami in Biomedical Engineering.  I worked for Siemens and Draeger in algorithm development on patient monitors. I then joined [Abiomed](http://abiomed.com), a cardiovascular devices developer and manufacturer where I started as a Senior Algorithm Designer and moved onto Project Management.  

I took CSCI E-12 last semester and I hope that this course will broaden my horizon by learning about the backend of web applications.  I hope to apply for the SW Engineering Masters by the end of this course.

Samer

**Comment by mcm223** [comment]
Hi all,

My name is Matt McGrath and I currently reside in Seattle, WA. I've worked at Amazon for the last five years, and I'm currently working as a networking business analyst in AWS. I've dabbled in technology for a long time but most of my formal education and experience has been in business and marketing. Since the winds of change seem to favor technology (particularly in Seattle) I've decided to double-down on it and pursue the IT ALM here at HES. This is my 10th course in the program, so the end is in sight! 

Outside of work I play drums in a local country band -- we're called Palatine Ave if you want to look us up on Spotify. And I recently have been experimenting with Raspberry Pi; my latest project is a temperature and humidity monitor to keep tabs on my apartment while I'm away, and I also use it as an ad-blocking local DNS server. 

Looking forward to the class!

**Comment by johnpura** [comment]
Hi All,

My name is John Pura and currently live in Western Massachusetts. I am taking this class to fulfill one of my required courses for the Web Technologies Certificate at HES. I am a very passionate coder and most interested in UI/UX design and building dynamic data-driven web applications. I have some PHP coding experience, but never used it along side a framework such as Laravel. So, I am looking forward to learning Laravel and adding it to my programming repertoire. After reading all the Introductions, it seems there is a wide range of experience and talents, so I am very eager to learn something from each of you and I hope I can provide the same.

Good luck!

-John

**Comment by taylormeyer** [comment]
Hi Everyone,

My name is Taylor Meyer and I live in Chapel Hill, North Carolina. I've recently completed my MBA degree at UNC Kenan-Flagler Business School. I also went to UNC for undergrad and played on the varsity tennis team, so if there are any tennis players out there let me know!

I currently work at Hyperspace Ventures and help manage a development team. I am looking to improve me technical skills so further advance in my career. I am looking forward to the class and learning lots of new things!

Best,
Taylor

**Comment by bwilks26** [comment]
The most important thing in my life is my family. I have been married for 18 years and three beautiful boys- Jackson 8, Cash 3, and Hutch 1. 

I am a BA, MBA and alumni of Stanford Graduate School of Business. I graduate in May with a Master in Digital Media from Harvard. My fields of experience span from hard core technology disciplines like assisting client sites across North America, Europe and Asia in optimizing their IT strategies to sophisticated consumer marketing industries ranging from packaging to entertainment.

As an entrepreneur CEO, I founded four companies and has equity positions in many others: Clear View Group a global packaging company, FreeForm Agency a marketing and design company working with notable entertainment brands, professional athletes, industrial manufacturing companies, and large non profit organizations, Sager Creek Packaging a procurement consulting company with four decades of collective experience, and SP Marketing a sales organization representing some of the largest manufactures in the world.

As a strategy and marketing consultant, I consulted with many fortune 500 companies. My work also includes numerous startups and VCs, and he played interim VP Marketing roles for several such ventures. I have a proven track record in both small private companies and divisions of larger companies.

As the Vice President of Business Development and Director of Marketing for two of the largest privately held companies in North America I created major growth strategies through new market penetration, M&A, and industry roll-ups.

As a inventor I marketed and developed many well-regarded methodologies for consumer goods which I have used repeatedly in different situations and across a variety of market segments.

I began my professional career in politics. I managed a high profile U.S. Congressional campaign in Texas, assisted U.S. House Majority Leader Dick Armey during the Contract With America , and served as the Executive Director of the Conservative Leadership Political Action Committee in Washington, D.C. where I was responsible for millions in annual contributions to US Senate, Congressional, and Presidential candidates. I graduated from the prestigious Leadership Institute (LI) where Morton Blackwell, LI’s founder, personally mentored me to teach workshops on marketing, campaigns, fundraising, grassroots organizing, youth politics, and communications around the world.

I am a college All-American, Coach C.L. Brigham Award recipient for outstanding athletic & academic achievement, and was recently selected as one of the Top 20 Leaders for being among the most prominent and successful leaders in business.

**Comment by reelmatt** [comment]
Hi everyone,

My name is Matthew, or Matt — I'm regularly called both. I got my undergraduate degree in Film/TV post-production and currently edit/produce educational video content. For the last year or so now I've been taking software engineering courses at the Extension school on a path towards hopefully earning a Masters degree, with CSCI E-15 being part of that path.

I look forward to working through the assignments and with you all over the course of this semester.

-Matt

**Comment by kylepg** [comment]
Hey guys, my name’s Kyle. I live right outside Boston and am currently working my dream job for the Boston Celtics as a front end developer & designer. 

Up until this point, my coding experience has been exclusively client-side. I’ve dabbled with node.js here and there, but the more I am exposed to back end technologies the more curious I become about how they work. It’s tough for me to be build things on the web and not know what's going on under the hood. Can’t wait to learn all about it and expand my skillset.

When I’m out from behind the computer I like to hike, skateboard, play basketball, play piano, and hang with my dog.

-Kyle

**Comment by gloverjason** [comment]
Hi, 

My name is Jason Glover.  I’m currently pursuing a master’s degree in Digital Media Design.  This is my second semester at Harvard Extension School.  Last semester, I took CSCI E-3 and CSCI E-12.  From those classes, I learned a great deal about front end development.  I’m taking this class so I can learn more about back end development.

In my free time, I like exercise, reading, hiking, and skiing.  I look forward to taking this class with you-all.

Jason

**Comment by oarangel** [comment]
Hello Everyone,

My name is Oscar Rangel and I live in Puerto Rico with my family. I have BSEE from Tulane university and a PE Licence from the State of Louisiana. I am Senior Controls Engineer for [BHGE]( https://www.bhge.com) where I write software for turbomachinery equipment used in the Power Generation Industry. 
With the rapidly changing web technology, I decided to pursue a Masters Degree in Software Engineering. This is my second course at HES.  I look forward to enhancing my PHP programming knowledge and  learning about server side web applications.

**Comment by tanyaflint** [comment]
Hi Everyone,

Very nice to meet you all. My name is Tanya Flint, I currently work as a Technology Project Manager, although I have plenty of hands-on web development experience specifically front-end development and back-end in .Net framework. So it will be interesting to compare it to Laravel.

Currently, I work in Wordpress and looking forward to learning PHP and very interested in learning Laravel. I occasionally take on freelance web development projects on the side. And that is one of the reasons to why I am taking this course, besides just loving to code and learning new technologies. I am hoping to use the skills I learn in this class at work and take on more complex freelance projects.

I like to go snowboarding, although with the busy schedule it’s been hard to get out to the slopes this year. I enjoy traveling and visiting new places. I am planning a trip to the Czech Republic in May, and possibly visit Germany, Austria, and Hungry while I am there!

I am looking forward to working with you all.

Tanya.

**Comment by jonbrowndeveloper** [comment]
Hello Ya'll,

My name is Jon Brown. I have been building software applications for a good 7 years starting out with good Ol' C and objective C. From there, I have done web design to working with numerous API's my favorite html/css version of which being Twitter's Bootstrap. I have done a bit of back end web design with PHP in the past (so this should be a good time), courses and work in .NET, and in the recent past I have moved on the Apple side to Swift 3. 

I also love to write music and hope to someday cross both wires of music and software development. Maybe write algorithms that mimic the composition process (although that been done and not too successfully) or write programs to help musicians or engage music listeners. 

Look forward to the class!

Jon

**Comment by charlie-harvard** [comment]
Hey Everyone,

My name is `Chutian Gao`. I am pursuing a Web Technology Certificate. E-15 is the 4th class I took in Harvard Ext. School. 

I am a Web Developer and working at Wellesley College. I've been developing PHP web applications for 2 years and haven't had a chance to use an industrial-grade framework. I'm looking forward to learning more advanced Web App development skills!

Thanks! So excited!

Charlie

**Comment by anup24** [comment]
Hello All,

My name is Anup Shetye and I am an IT professional. I did my bachelors in engineering and have more than 10 years of software development experience which includes Java and related technologies. I am looking forward to advance my web application skills and learn new things from this class. This is my second course towards my graduate degree course.

In my free time, I read books and listen to music.

Anup

**Comment by hsayres** [comment]
Hi! My name is Haley and I'm a Product Manager at a cybersecurity startup in SF. I have my BS and MA from Stanford and look forward to taking this class for my personal & professional development.

**Comment by bwilks26** [comment]
Hi Haley, I’m Alumni of Stanford Business School. Nice to have fellow Alumni in the class ;-) 

Bryan Wilks
918-808-4375

**Comment by aleksaleksiev** [comment]
Hi folks,

I'm Aleks. At the moment I'm at law school in Australia. I've dabbled in programming in the past but I wanted to formalise my knowledge, so I signed up to this course. 

Outside of this, I'm a fan of basketball (and the Celtics in particular @kylepg ).

**Comment by JoelTurnblade** [comment]
Hi my name is Joel Turnblade,

I would classify myself as a math geek.  I did my undergrad at the University of Arizona and double majored in Mechanical Engineering and Mathematics.  My strongest interest is in formal logic, complex analysis, and computability.  After I graduated, I spent a little over a year working as a mechanical engineer in Tucson AZ.  I also met and married my wife Kaitlyn.  Outside of work and academics, I love to hike when it’s not too hot outside, and to ski.

I am taking this class as one of the requirements for the Software Engineering masters program.  I did a pretty reasonable amount of programming in school and in my free time, and I really forward to using it in my career!

**Comment by prashantsmore** [comment]
Hi Course mates,
My name is Prashant More. I am from Mumbai, India and currently reside in Natick Mass.  I completed my Bachelors in Computer Engineering from India . I always wanted to take  a masters course in Information Science and I feel this course will be a stepping stone in that direction.

Looking forward to work , learn and have fun with you all

**Comment by jaechong** [comment]
Hello everyone,

My name is **Jae Chong**.  I live in Toronto, Ontario.  I am taking CSCI E15 and E31 together this term after taking E3 and E12.  I hope to learn more on the back-end side of web development.
I started taking Harvard Extension courses after retiring a year ago.  I don't plan on going back to work but I still like to learn and explore.  I was a software engineer for more than 30 years mostly working on the low level system and video BIOS.  I haven't decided yet but I will probably pursue a master degree in Digital Media Design.

Good luck everyone, hope we have fun and get to know each other better.

**Comment by archerdave** [comment]
Hi, my name is David.  I live in eastern Massachusetts.  I've been sticking my head in on various technologies for quite some time, and love to be "elbows deep" in tinkering and making things work.  Looking forward to the course!

**Comment by diddydear** [comment]
Hi Everyone, 
My name is Edidiong. I'm Nigerian and I live in Abuja. I'm taking this course as part of the prerequisite course in fulfilling my degree requirement. I'm enthusiastic about programming because of my interest in web GIS. I hope to develop solutions that can solve real live problems especially in the environment domain. 

Looking forward to a successful semester.

**Comment by erikj462** [comment]
hey everyone,
erik johnson here, i am from the beautiful smokey mountains (Asheville nc).

**Comment by rreyneke** [comment]
Hi folks,

My name is Rupert Reyneke. I'm living in Yorba Linda, California. I've been at Extension for abut 2 years now and this is one of my final courses in the Digital Media Design degree. I'm excited about taking this course and look forward to collaborating.

Best of luck and success to you all this semester!
