### ISSUE TITLE
Failed SQL connection - not recognizing changes to .env

### ISSUE THREAD

**Issue by oarangel** [susanBuck/dwa15-spring2018#55]
Trying to complete the "Local database configuration" lecture notes, the following error message is displayed: 
```
array:4 [▼
  "Environment" => "local"
  "Database defaultStringLength" => 255
  "MySQL connection config" => array:12 [▼
    "driver" => "mysql"
    "host" => "127.0.0.1"
    "port" => "3306"
    "database" => "homestead"
    "username" => "homestead"
    "password" => "secret"
    "unix_socket" => ""
    "charset" => "utf8mb4"
    "collation" => "utf8mb4_unicode_ci"
    "prefix" => ""
    "strict" => true
    "engine" => null
  ]
  "Database connection test" => "FAILED: SQLSTATE[HY000] [1045] Access denied for user 'homestead'@'localhost' (using password: YES) (SQL: SHOW DATABASES;)"
]
```

My env files looks like:
```
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=foobooks
DB_USERNAME=root
DB_PASSWORD=root
```
Somehow the configuration is binding to another configuration but I am not sure which file is providing those DB settings. e.g. **"Homestead"** I noticed the original .env.example  file had a ` Homestead` DB setting but I deleted the file

**Comment by oarangel** [comment]
Hello @ElijahMR, as suggested, I cleared the cache and the  issue went away. That probably means the _SQL_ was binding to the initial `.env.example` profile and a the cache needed to be cleared for the database to connect to the new configuration.

**Comment by susanBuck** [comment]
Good find, @ElijahMR! Oscar and I were working on this last night in chat, and I didn't even think to try that. 

This is the first semester where we've run into needing to run `artisan config:cache` locally. When I get a free moment I'll look deeper into how the config is being cached, because I've yet to identify a pattern for when it needs to be cleared. 

For example, you all saw me edit the .env in lecture when setting up the DB and no clearing was needed. Yet, in Oscar's case (and I'm sure others) it is needed.

I added a note to the [config/env notes 22 days ago](https://github.com/susanBuck/dwa15-spring2018/commit/8f096b836fa377a07440f1e15efba9df09041044#diff-2048b15570a382a470939c8fd73dcd9a) about possibly needing to run this command. I'll update the local db config notes with a reminder about this.

Thanks Oscar for drawing this to my attention!

**Comment by susanBuck** [comment]
I spent some time digging through the framework source code, but I've yet to identify what might trigger the cache to stick, aside from manually running `artisan config:cach`. 

I'll continue to keep my eye out for a rhyme/reason to the caching system, but in the meantime, we know `artisan config:cache` does the trick so I'll close this thread.
