### ISSUE TITLE
Choosing routes when more than one is defined

### ISSUE THREAD

**Issue by archerdave** [susanBuck/dwa15-spring2018#56]
In my ```web.php```, I accidentally set two routes to use the same URI, like so:

```php
Route::get('/', 'Controller@index');
Route::get('/', 'Controller@other');
```
This was discovered when I was getting the view referenced by ```other``` and not the one referenced by ```index```.  However, I thought Laravel would use the first route that matched the URI, which in this case would be ```index```.  So, I'm confused.  Do I have the route selection model wrong in my head, or is something else possibly going on?

*Obviously the fix is to correct the URI, but I'm trying to understand the behavior I observed.*

**Comment by susanBuck** [comment]
If two routes are ambiguous, you will see the first route matched.

For example, technically `/test/a` would match both of the following routes, but because the "A" one comes first, it takes precedence:

```
Route::get('/test/a', function() {
    return 'A';
});
Route::get('/test/{b}',  function() {
    return 'B';
});
```

In your example, though, it's not so much that you have ambiguous routes as you have redundant routes. In that case the second one overrides the first one when the route map is created.

**Comment by archerdave** [comment]
Ah, I see the difference.  Got it!  Thanks!
