### ISSUE TITLE
php artisan exception question (when running `route:cache`)

### ISSUE THREAD

**Issue by gaderrick** [susanBuck/dwa15-spring2018#65]
In running the command `php artisan route:cache`, I'm seeing an exception being thrown in the foobooks project that looks like this:

> LogicException  : Unable to prepare route [api/user] for serialization. Uses Closure.

Doing a search of google it looks like the problem is with the api.php file, but I'm not sure how to fix it. It doesn't appear to be impacting the application though. Any ideas?

**Comment by susanBuck** [comment]
Open `/routes/api.php` and delete or comment out the following route:

```php
Route::middleware('auth:api')->get('/user', function (Request $request) {
    return $request->user();
});
```

This routes file is a different routes file then the one we've been using - it's used for if you designed your app to have an API.

The problem is it contains a route with a closure, which, as the exception indicated, can not be cached.

As for why Laravel includes a route "out of the box" that can't be cached causing an error when this command is run - well, I have no idea - seems kind of silly if you ask me. : )

**Comment by gaderrick** [comment]
Thanks!
