### ISSUE TITLE
Issue with <? Tags on Production

### ISSUE THREAD

**Issue by brianyingling** [susanBuck/dwa15-spring2018#7]
Hello everyone,

I ran into an issue where shortcut `<?` tags worked properly, but when I pushed to production the contents within those `<?` tags were not being displayed. I had to change them to `<?php` tags for the contents to display properly. I'm not sure what the cause is, but I imagine it's a setting somewhere in Apache.

**Comment by susanBuck** [comment]
Good observation, Brian. You are correct in that this does come down to a setting, but it's a php setting, not Apache. 

The `<?` (without the PHP) is called a short-open tag and they can be enabled/disabled in your `php.ini` file following the same procedures described in this note set: [Error reporting & configs](https://github.com/susanBuck/dwa15-spring2018/blob/master/php/error-reporting-and-configs.md).

As you discovered, your local install of PHP must have short-open tags enabled, while the install of PHP we have on DigitalOcean has them disabled by default.

This is a great example of a codebase working perfectly fine in one environment but then the exact same code failing in another environment. Because of gotchas like this, there are platforms (like [Docker](https://www.docker.com/)) that allow you to exactly replicate server settings across different environments to make sure everything is consistent. Not something we need in the scope we're working, but something to have on your radar for complex, real-world applications.

Going back to the short-open tags, it's now best practices in PHP to always use the long open tag (`<?php`).  Given that, it'd be my recomendation to switch your code to the long open tag, rather than configuring your DigitalOcean server to work with the short-open tags.

**Comment by susanBuck** [comment]
An addendum to the above, related to the discussion of [alternative syntax](https://github.com/susanBuck/dwa15-spring2018/blob/master/php/php-and-html.md#alternative-syntax) in php...

Note that the `<?=` shortcut for echo, while it looks similar to a short-open tag, is not actually a short-open tag. It will work regardless of your short-open tag settings.
